activity_homepage:
    path:     /
    defaults: { _controller: ActivityBundle:Default:index }

activity_activity_add:
    path:     /add
    defaults: { _controller: ActivityBundle:Activity:add }

activity_activity_remove:
    path:     /remove
    defaults: { _controller: ActivityBundle:Activity:remove }

activity_activity_display:
    path:     /display
    defaults: { _controller: ActivityBundle:Activity:display }

activity_activity_single_display:
    path:     /single
    defaults: { _controller: ActivityBundle:Activity:single }

activity_activity_single_likes_display:
    path:     /singlelikes
    defaults: { _controller: ActivityBundle:Activity:likes }

activity_activity_single_deslikes_display:
    path:     /singledeslikes
    defaults: { _controller: ActivityBundle:Activity:deslikes }

activity_activity_addrating:
    path:     /addrating
    defaults: { _controller: ActivityBundle:Activity:addrating }