<?php

namespace ActivityBundle\Repository;

/**
 * DeslikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeslikesRepository extends \Doctrine\ORM\EntityRepository
{
    public function Finddeslike($iduser, $idact){
        $query=$this->getEntityManager()
            ->createQuery("select m from ActivityBundle:Deslikes m where m.idAct='$idact' AND m.idUser='$iduser'");
        return $query->getResult();
    }
}
