<?php

namespace ActivityBundle\Repository;

/**
 * EvalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvalRepository extends \Doctrine\ORM\EntityRepository
{
}
