<?php

namespace ActivityBundle\Repository;

/**
 * LikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesRepository extends \Doctrine\ORM\EntityRepository
{
    public function Findlikes($iduser, $idact){
        $query=$this->getEntityManager()
            ->createQuery("select m from ActivityBundle:Likes m where m.idAct='$idact' AND m.inUser='$iduser'");
        return $query->getResult();
    }
}
